In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([ 0.65634762,  1.33677815, -0.52984618, -1.59660829, -0.29875269,
        0.14297393, -1.03316745,  1.25749855,  0.36341182,  0.45906674])

In [6]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-1.21289048,  0.49801542,  1.7556355 , -0.35285334, -1.0472398 ,
       -0.97029989,  0.61501969, -0.02175736,  0.19146854, -0.42324448])

In [7]:
#Addition
np.add(A,B)

array([-0.55654286,  1.83479357,  1.22578932, -1.94946162, -1.34599249,
       -0.82732596, -0.41814776,  1.23574119,  0.55488036,  0.03582226])

In [8]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.65634762,  1.33677815,  1.7556355 , -0.35285334, -0.29875269,
        0.14297393,  0.61501969,  1.25749855,  0.36341182,  0.45906674])

In [9]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True